namespace Glamourer.Customization;

// Localization from the game files directly.
public enum CustomName
{
    MidlanderM,
    HighlanderM,
    WildwoodM,
    DuskwightM,
    PlainsfolkM,
    DunesfolkM,
    SeekerOfTheSunM,
    KeeperOfTheMoonM,
    SeawolfM,
    HellsguardM,
    RaenM,
    XaelaM,
    HelionM,
    LostM,
    RavaM,
    VeenaM,
    MidlanderF,
    HighlanderF,
    WildwoodF,
    DuskwightF,
    PlainsfolkF,
    DunesfolkF,
    SeekerOfTheSunF,
    KeeperOfTheMoonF,
    SeawolfF,
    HellsguardF,
    RaenF,
    XaelaF,
    HelionF,
    LostF,
    RavaF,
    VeenaF,
}
