namespace Glamourer.Customization
{
    public enum CustomName
    {
        Clan = 0,
        Gender,
        Reverse,
        OddEyes,
        IrisSmall,
        IrisLarge,
        IrisSize,
        MidlanderM,
        HighlanderM,
        WildwoodM,
        DuskwightM,
        PlainsfolkM,
        DunesfolkM,
        SeekerOfTheSunM,
        KeeperOfTheMoonM,
        SeawolfM,
        HellsguardM,
        RaenM,
        XaelaM,
        HelionM,
        LostM,
        RavaM,
        VeenaM,
        MidlanderF,
        HighlanderF,
        WildwoodF,
        DuskwightF,
        PlainsfolkF,
        DunesfolkF,
        SeekerOfTheSunF,
        KeeperOfTheMoonF,
        SeawolfF,
        HellsguardF,
        RaenF,
        XaelaF,
        HelionF,
        LostF,
        RavaF,
        VeenaF,

        Num,
    }
}
