using System;

namespace Glamourer
{
    [Flags]
    public enum CharacterFlag : ulong
    {
        MainHand  = 1ul << 0,
        OffHand   = 1ul << 1,
        Head      = 1ul << 2,
        Body      = 1ul << 3,
        Hands     = 1ul << 4,
        Legs      = 1ul << 5,
        Feet      = 1ul << 6,
        Ears      = 1ul << 7,
        Neck      = 1ul << 8,
        Wrists    = 1ul << 9,
        RFinger   = 1ul << 10,
        LFinger   = 1ul << 11,
        ModelMask = (1ul << 12) - 1,

        StainMainHand = MainHand << 16,
        StainOffHand  = OffHand << 16,
        StainHead     = Head << 16,
        StainBody     = Body << 16,
        StainHands    = Hands << 16,
        StainLegs     = Legs << 16,
        StainFeet     = Feet << 16,
        StainEars     = Ears << 16,
        StainNeck     = Neck << 16,
        StainWrists   = Wrists << 16,
        StainRFinger  = RFinger << 16,
        StainLFinger  = LFinger << 16,
        StainMask     = ModelMask << 16,
        EquipMask     = ModelMask | StainMask,

        Race              = 1ul << 32,
        Gender            = 1ul << 33,
        BodyType          = 1ul << 34,
        Height            = 1ul << 35,
        Clan              = 1ul << 36,
        Face              = 1ul << 37,
        Hairstyle         = 1ul << 38,
        Highlights        = 1ul << 39,
        SkinColor         = 1ul << 40,
        EyeColorRight     = 1ul << 41,
        HairColor         = 1ul << 42,
        HighlightsColor   = 1ul << 43,
        FacialFeatures    = 1ul << 44,
        TattooColor       = 1ul << 45,
        Eyebrows          = 1ul << 46,
        EyeColorLeft      = 1ul << 47,
        EyeShape          = 1ul << 48,
        IrisSize          = 1ul << 49,
        NoseShape         = 1ul << 50,
        JawShape          = 1ul << 51,
        MouthShape        = 1ul << 52,
        Lipstick          = 1ul << 53,
        LipColor          = 1ul << 54,
        MuscleMass        = 1ul << 55,
        TailShape         = 1ul << 56,
        BustSize          = 1ul << 57,
        FacePaint         = 1ul << 58,
        FacePaintReversed = 1ul << 59,
        FacePaintColor    = 1ul << 60,
        CustomizeMask     = ((1ul << 61) - 1) & ~EquipMask,
    }
}
