namespace Glamourer.GameData;

/// <summary> For localization from the game files directly. </summary>
public enum CustomName
{
    MidlanderM,
    HighlanderM,
    WildwoodM,
    DuskwightM,
    PlainsfolkM,
    DunesfolkM,
    SeekerOfTheSunM,
    KeeperOfTheMoonM,
    SeawolfM,
    HellsguardM,
    RaenM,
    XaelaM,
    HelionM,
    LostM,
    RavaM,
    VeenaM,
    MidlanderF,
    HighlanderF,
    WildwoodF,
    DuskwightF,
    PlainsfolkF,
    DunesfolkF,
    SeekerOfTheSunF,
    KeeperOfTheMoonF,
    SeawolfF,
    HellsguardF,
    RaenF,
    XaelaF,
    HelionF,
    LostF,
    RavaF,
    VeenaF,
}
