name: Create Release

on:
  push:
    tags:
      - testing_*

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Prepare Environment
        uses: xivdev/Penumbra/.github/actions/prepare-environment@master
        with:
          dalamud-distrib: stg/
      - name: Build and Upload Artifact
        uses: xivdev/Penumbra/.github/actions/build-with-artifact@master
        with:
          configuration: Debug
          project: Glamourer
          version: ${{ github.ref_name }}
      - name: Create Release
        uses: xivdev/Penumbra/.github/actions/create-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: Glamourer
          version: ${{ github.ref_name }}
      - name: Update repo.json
        uses: xivdev/Penumbra/.github/actions/update-repo@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project: Glamourer
          version: ${{ github.ref_name }}
          testing: true